packages:
  - '.'
  - 'benchmarks/synthetic-web-bundler-benchmark'
  - 'config'
  - 'examples/*'
  - 'examples/federation/*'
  - 'tests/react-router-framework/integration'
  - 'tests/react-router-framework/integration/helpers/rsbuild-template'
  - 'tests/react-router-framework/integration/helpers/rsc-framework'
  - 'tests/react-router-framework/integration/helpers/rsc-preview'
