name: pkg.pr.new

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: pkg-pr-new-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish preview package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.nvmrc'

      - name: Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Publish preview package
        run: pnpm exec pkg-pr-new publish --commentWithSha --packageManager=pnpm
